import Foundation
import Testing
@testable import LedFan

/// Golden bytes from pearlfan-rs (commit 3d9b32c, MIT/Apache-2.0) through the harness in
/// Tools/PearlFanGolden: the same pixel grids our rasterizer produces, drawn with the reference
/// library's `Frame::draw_point`, framed as its `Device::send_animation` frames them. Fonts differ
/// between the two projects, so the grids are the shared input and the bytes are the contract.
struct PearlFanEncoderGoldenTests {
    private let encoder = PearlFanEncoder()
    private func message(_ text: String, slot: Int = 0) throws -> FanMessage { try FanMessage(slot: slot, text: text) }
    private func hex(_ reports: [[UInt8]]) -> String {
        reports.map { $0.map { String(format: "%02X", $0) }.joined(separator: " ") }.joined(separator: "\n")
    }
    private func golden(_ text: String) -> String { text.trimmingCharacters(in: .whitespacesAndNewlines) }

    @Test func anEmptySlotIsABlankImage() throws {
        #expect(hex(try encoder.reports(for: [message("")])) == golden(Self.empty))
    }

    @Test func theLetterA() throws {
        #expect(hex(try encoder.reports(for: [message("A")])) == golden(Self.letterA))
    }

    @Test func aFullTwentySixCharacterMessage() throws {
        #expect(hex(try encoder.reports(for: [message("THE QUICK BROWN FOX JUMPS!")])) == golden(Self.twentySix))
    }

    @Test func helloWillieTheFirstSend() throws {
        #expect(hex(try encoder.reports(for: [message("HELLO WILLIE")])) == golden(Self.helloWillie))
    }

    @Test func twoMessagesInSlotsZeroAndOne() throws {
        let messages = [try message("A", slot: 0), try message("THE QUICK BROWN FOX JUMPS!", slot: 1)]
        #expect(hex(try encoder.reports(for: messages)) == golden(Self.twoImages))
    }

    /// D19: a Send publishes all eight slots. The reference numbers images 0–7 in order.
    @Test func allEightSlotsWithLowercaseAndEmptyOnesAsBlankImages() throws {
        let texts = ["Hello World. I hold 8 Msg.", "26 letters in each Msg", "I'm your *NOTE PAD*", "*Mom Pick me up @4P*",
                     "HELLO WILLIE", "Slot six", "Slot seven", "Slot eight"]
        let messages = try texts.enumerated().map { try FanMessage(slot: $0.offset, text: $0.element) }
        let reports = try encoder.reports(for: messages)
        #expect(reports.count == 8 * PearlFanEncoder.reportsPerImage)
        #expect(hex(reports) == golden(Self.eightSlots))
    }

    @Test func emptySlotsInAnEightSlotSendAreBlankImagesNotOmitted() throws {
        let messages = try (0..<8).map { try FanMessage(slot: $0, text: $0 == 3 ? "X" : "") }
        let reports = try encoder.reports(for: messages)
        #expect(reports.count == 320)
        #expect(reports[3 * 40][3] == 0x03, "the fourth header carries image id 3")
        #expect(reports[0 * 40 + 1] == [UInt8](repeating: 0xFF, count: 8), "an empty slot is all blank columns")
    }

    // MARK: - Reference output, verbatim

    static let eightSlots = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FF E7
FF E7 FF FF FF FF FF 07
FF 6B FF 6B FF 6B FF 9F
FF FF FF EF FF 57 FF 57
FF 57 FF B7 FF FF FC 07
FE FF FF 3F FE FF FC 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FE 4F
FD B7 FD B7 FD B7 FE 4F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FC 07
FF B7 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FF 87 FF 7F FF 7F
FF BF FC 07 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FD F7 FC 07
FD F7 FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF E7
FF E7 FF FF FF FF FC 07
FF B7 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FF BF
FF 7F FF 7F FF BF FF 07
FF FF FF 8F FF 77 FF 77
FF 77 FF 8F FF FF FC 0F
FF F7 FF 8F FF F7 FC 0F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FF FF
FF F7 FC 07 FD F7 FF FF
FF FF FF 9F FF 57 FF 57
FF 57 FF 8F FF FF FC 07
FF BF FF BF FF BF FC 07
A0 10 00 01 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 07 FF 6B FF 6B
FF 6B FF 9F FF FF FF EF
FF 57 FF 57 FF 57 FF B7
FF FF FC 07 FE FF FF 3F
FE FF FC 07 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 87 FF 7F FF 7F
FF BF FC 07 FF FF FF EF
FF 77 FF 77 FF 77 FF 8F
FF FF FF 87 FF 57 FF 57
FF 57 FF EF FF FF FF 9F
FF 57 FF 57 FF 57 FF 8F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF 87
FF 7F FF 7F FF BF FF 07
FF FF FF FF FF F7 FD 07
FF 77 FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF EF FF 57 FF 57
FF 57 FF B7 FF FF FF BF
FF 7F FF 7F FF BF FF 07
FF FF FF 9F FF 57 FF 57
FF 57 FF 8F FF FF FF EF
FF F7 FF 77 FC 0F FF 7F
FF FF FF EF FF F7 FF 77
FC 0F FF 7F FF FF FF 9F
FF 57 FF 57 FF 57 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF CF FD B7 FD B7
FE B7 FF 0F FF FF FE 77
FD B7 FD D7 FD E7 FE F7
A0 10 00 02 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF 5F
FF BF FE 0F FF BF FF 5F
FF FF FF 1F FE EF FD F7
FD F7 FC 07 FF FF FE 07
FD DF FD DF FD DF FE 07
FF FF FE 7F FD BF FD BF
FD BF FC 07 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FD F7 FD B7 FD B7
FD B7 FC 07 FF FF FD FF
FD FF FC 07 FD FF FD FF
FF FF FE 0F FD F7 FD F7
FD F7 FE 0F FF FF FC 07
FF DF FF BF FF 7F FC 07
FF FF FF 5F FF BF FE 0F
FF BF FF 5F FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF BF FF 7F FF 7F
FF BF FF 07 FF FF FF 07
FF EF FF F7 FF F7 FF 0F
FF FF FF 8F FF 77 FF 77
FF 77 FF 8F FF FF FF 07
FF EB FF EB FF EB FF 1B
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF 87
FF 7F FF 9F FF 7F FF 07
FF FF FF FF FF FF FC FF
FD 7F FF FF FF FF FF FF
FD F7 FC 07 FD F7 FF FF
A0 10 00 03 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 5F FF BF FE 0F
FF BF FF 5F FF FF FE 7F
FD BF FD BF FD BF FC 07
FF FF FF DF FC 07 FE DF
FF 5F FF 9F FF FF FE 0F
FD F7 FD 87 FD B7 FE CF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF 9F
FF 6F FF 6F FF 6F FF 03
FF FF FF 07 FF EF FF F7
FF F7 FF 0F FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 9F FF 57 FF 57
FF 57 FF 8F FF FF FF 87
FF 7F FF 9F FF 7F FF 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF 77 FF AF FF DF FC 07
FF FF FF EF FF 77 FF 77
FF 77 FF 8F FF FF FF FF
FF F7 FD 07 FF 77 FF FF
FF FF FE 7F FD BF FD BF
FD BF FC 07 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 87 FF 7F FF 9F
FF 7F FF 07 FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FC 07 FE FF FF 3F
FE FF FC 07 FF FF FF 5F
FF BF FE 0F FF BF FF 5F
A0 10 00 04 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FD F7 FD B7 FD B7
FD B7 FC 07 FF FF FF FF
FD F7 FC 07 FD F7 FF FF
FF FF FF F7 FF F7 FF F7
FF F7 FC 07 FF FF FF F7
FF F7 FF F7 FF F7 FC 07
FF FF FF FF FD F7 FC 07
FD F7 FF FF FF FF FC 0F
FF F7 FF 8F FF F7 FC 0F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FE 0F
FD F7 FD F7 FD F7 FE 0F
FF FF FF F7 FF F7 FF F7
FF F7 FC 07 FF FF FF F7
FF F7 FF F7 FF F7 FC 07
FF FF FD F7 FD B7 FD B7
FD B7 FC 07 FF FF FC 07
FF BF FF BF FF BF FC 07
A0 10 00 05 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 77 FF AF FF DF
FF AF FF 77 FF FF FF FF
FF F7 FD 07 FF 77 FF FF
FF FF FF EF FF 57 FF 57
FF 57 FF B7 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF EF FF F7 FF 77
FC 0F FF 7F FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FD CF
FD B7 FD B7 FD B7 FE 77
A0 10 00 06 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF 87 FF 7F FF 7F
FF BF FF 07 FF FF FF 9F
FF 57 FF 57 FF 57 FF 8F
FF FF FF 1F FF EF FF F7
FF EF FF 1F FF FF FF 9F
FF 57 FF 57 FF 57 FF 8F
FF FF FF EF FF 57 FF 57
FF 57 FF B7 FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF EF FF F7 FF 77
FC 0F FF 7F FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FD CF
FD B7 FD B7 FD B7 FE 77
A0 10 00 07 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF EF FF F7 FF 77
FC 0F FF 7F FF FF FF 87
FF 7F FF 7F FF BF FC 07
FF FF FF 07 FF 6B FF 6B
FF 6B FF 9F FF FF FF FF
FF F7 FD 07 FF 77 FF FF
FF FF FF 9F FF 57 FF 57
FF 57 FF 8F FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF EF FF F7 FF 77
FC 0F FF 7F FF FF FF 8F
FF 77 FF 77 FF 77 FF 8F
FF FF FF FF FF F7 FC 07
FD F7 FF FF FF FF FD CF
FD B7 FD B7 FD B7 FE 77

"""

    static let empty = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
"""

    static let letterA = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FE 07
FD DF FD DF FD DF FE 07
"""

    static let twentySix = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FC 17
FF FF FF FF FF FF FD CF
FD B7 FD B7 FD B7 FE 77
FF FF FE 7F FD BF FD BF
FD BF FC 07 FF FF FC 07
FE FF FF 3F FE FF FC 07
FF FF FC 0F FF F7 FF F7
FF F7 FC 0F FF FF FD FF
FC 0F FD F7 FF F7 FF EF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FC E7
FF 5F FF BF FF 5F FC E7
FF FF FE 0F FD F7 FD F7
FD F7 FE 0F FF FF FD FF
FD BF FD BF FD BF FC 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FC 07
FF DF FF BF FF 7F FC 07
FF FF FC 0F FF F7 FF 8F
FF F7 FC 0F FF FF FE 0F
FD F7 FD F7 FD F7 FE 0F
FF FF FE 77 FD AF FD 9F
FD BF FC 07 FF FF FE 4F
FD B7 FD B7 FD B7 FC 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FD F7
FE EF FF 5F FF BF FC 07
FF FF FE EF FD F7 FD F7
FD F7 FE 0F FF FF FF FF
FD F7 FC 07 FD F7 FF FF
FF FF FC 0F FF F7 FF F7
FF F7 FC 0F FF FF FE 17
FD EF FD D7 FD F7 FE 0F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FD F7
FD B7 FD B7 FD B7 FC 07
FF FF FC 07 FF BF FF BF
FF BF FC 07 FF FF FD FF
FD FF FC 07 FD FF FD FF
"""

    static let helloWillie = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FD F7 FD B7 FD B7
FD B7 FC 07 FF FF FF FF
FD F7 FC 07 FD F7 FF FF
FF FF FF F7 FF F7 FF F7
FF F7 FC 07 FF FF FF F7
FF F7 FF F7 FF F7 FC 07
FF FF FF FF FD F7 FC 07
FD F7 FF FF FF FF FC 0F
FF F7 FF 8F FF F7 FC 0F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FE 0F
FD F7 FD F7 FD F7 FE 0F
FF FF FF F7 FF F7 FF F7
FF F7 FC 07 FF FF FF F7
FF F7 FF F7 FF F7 FC 07
FF FF FD F7 FD B7 FD B7
FD B7 FC 07 FF FF FC 07
FF BF FF BF FF BF FC 07
"""

    static let twoImages = """
A0 10 00 00 55 00 00 00
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FE 07
FD DF FD DF FD DF FE 07
A0 10 00 01 55 00 00 00
FF FF FF FF FF FF FC 17
FF FF FF FF FF FF FD CF
FD B7 FD B7 FD B7 FE 77
FF FF FE 7F FD BF FD BF
FD BF FC 07 FF FF FC 07
FE FF FF 3F FE FF FC 07
FF FF FC 0F FF F7 FF F7
FF F7 FC 0F FF FF FD FF
FC 0F FD F7 FF F7 FF EF
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FC E7
FF 5F FF BF FF 5F FC E7
FF FF FE 0F FD F7 FD F7
FD F7 FE 0F FF FF FD FF
FD BF FD BF FD BF FC 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FC 07
FF DF FF BF FF 7F FC 07
FF FF FC 0F FF F7 FF 8F
FF F7 FC 0F FF FF FE 0F
FD F7 FD F7 FD F7 FE 0F
FF FF FE 77 FD AF FD 9F
FD BF FC 07 FF FF FE 4F
FD B7 FD B7 FD B7 FC 07
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FD F7
FE EF FF 5F FF BF FC 07
FF FF FE EF FD F7 FD F7
FD F7 FE 0F FF FF FF FF
FD F7 FC 07 FD F7 FF FF
FF FF FC 0F FF F7 FF F7
FF F7 FC 0F FF FF FE 17
FD EF FD D7 FD F7 FE 0F
FF FF FF FF FF FF FF FF
FF FF FF FF FF FF FD F7
FD B7 FD B7 FD B7 FC 07
FF FF FC 07 FF BF FF BF
FF BF FC 07 FF FF FD FF
FD FF FC 07 FD FF FD FF
"""
}
